# The first line is used for comment

# CUSTOM Archetype
!setname 0xf14 Perfect Sync
!setname 0xFA0 Yamimakai

# ==========================================================
# CONFIG ARCHETYPE CUSTOM - SOLO LEVELING SERIES
# ==========================================================

# 3000 (Ma goc)
!setname 0xBB8 Solo Leveling

# 3001
!setname 0xBB9 Shadow Army

# 196676536 (Ghep 0xBB9 + 0xBB8)
!setname 0xBB90BB8 Solo Leveling | Shadow Army

# 12454840 (Ghep 0xBE + 0xBB8)
!setname 0xBE0BB8 Solo Leveling | Monarch
